### ISSUE TITLE
你的胆量见识决定该项目根本没有什么前途

### ISSUE THREAD

**Issue by akeliduo** [BlinkDL/ChatRWKV#101]
加入了你的研发群里，仅提下病毒溯源就被踢出群了。

从你的见识和胆量，可以看出该项目根本不会有什么前途。一是没有开放性；二是不可接收异常事件，无法吸收其他优势。

记录下，几年后来看。

**Comment by cryscan** [comment]
乐

**Comment by akeliduo** [comment]
> 乐

你身在国外，也不敢碰那谁给你的”红线“（而且根本没人说是红线），自动避让，自动阉割，乐啥呢？乐大家都得病，你不敢提？提都不敢提！

**Comment by Sunbread** [comment]
我谔谔，，，既然你都表明你的政治立场，建议你出门左转[这个项目](https://github.com/cocktailpeanut/dalai)，，，，，

你要搞清楚那是QQ群，，，

**Comment by akeliduo** [comment]
> 我谔谔，，，既然你都表明你的政治立场，建议你出门左转[这个项目](https://github.com/cocktailpeanut/dalai)，，，，，
> 
> 你要搞清楚那是QQ群，，，

QQ群也有说什么事情不可以谈吗？压制别人的言论有理了？何况哪里可以看出是”政治立场“？

**Comment by Sunbread** [comment]
> > 我谔谔，，，既然你都表明你的政治立场，建议你出门左转[这个项目](https://github.com/cocktailpeanut/dalai)，，，，，
> > 你要搞清楚那是QQ群，，，
> 
> QQ群也有说什么事情不可以谈吗？压制别人的言论有理了？何况哪里可以看出是”政治立场“？

你既然觉得没什么事情不可以谈，有本事就别在你的消息里加分隔符，，，

**Comment by akeliduo** [comment]
> > > 我谔谔，，，既然你都表明你的政治立场，建议你出门左转[这个项目](https://github.com/cocktailpeanut/dalai)，，，，，
> > > 你要搞清楚那是QQ群，，，
> > 
> > 
> > QQ群也有说什么事情不可以谈吗？压制别人的言论有理了？何况哪里可以看出是”政治立场“？
> 
> 你既然觉得没什么事情不可以谈，有本事就别在你的消息里加分隔符，，，

当然有本事了，但是我喜欢加，你吹吧。

**Comment by akeliduo** [comment]
> 乐

别以为你躲着就好，你压制被人言论这件事，你不公开向我道歉，我一定找到密西根大学，问问是不是他们的价值观，看看你的做法得不得到他们的支持。

**Comment by BlinkDL** [comment]
？？？我根本不知道这个事情，我在睡觉

**Comment by Sunbread** [comment]
> > > > 我谔谔，，，既然你都表明你的政治立场，建议你出门左转[这个项目](https://github.com/cocktailpeanut/dalai)，，，，，
> > > > 你要搞清楚那是QQ群，，，
> > > 
> > > 
> > > QQ群也有说什么事情不可以谈吗？压制别人的言论有理了？何况哪里可以看出是”政治立场“？
> > 
> > 
> > 你既然觉得没什么事情不可以谈，有本事就别在你的消息里加分隔符，，，
> 
> 当然有本事了，但是我喜欢加，你吹吧。

什么阿Q精神胜利法，，，

**Comment by Aknifejackzhmolong** [comment]
我这个说话比较直，你就是个恨过言论洗脑下出生的出生而已，上帝保佑我评价你的自由

**Comment by gg22mm** [comment]
QQ微调群就是X B ，  几个x b 就在那里 说开源，  收费说事  。 问的问题都是避重就轻。 我想说说的好的问，说不好就是交流的地方， 就在那里怼， 都是站在道德最高点上去指点。从来没见的  。  反正我已经退出来了

其它我是看好各种框架百家齐放，也非常感谢发启人开源的精神，我都没有用来训练，不敢说什么。 现在有个问题就是对于多轮对话格式怎么配置？

如下对话数据
arrays=[

    
    [
		"病人：你叫什么名字",
		"医生：我叫小王"
	],	
	[
		"病人：1+1=？",
		"医生：等于二",
		"病人：不是3吗？",
		"医生：不是哦，别搞错了",
		"病人：好的谢",
		"医生：不用客气"
	],
    [
		"病人：今天星期八",
		"医生：你该吃药了",
		"病人：刚吃完",
		"医生：再来点",
		"病人：不要",
		"医生：要的"
	]
]

---------

多轮格式是这样吗？
train.txt内容如下：
Bob: 病人：你叫什么名字\n\nAlice: 医生：我叫小王
Bob: 病人：1+1=？\n\nAlice:医生：等于二\n\nBob:病人：不是3吗？\n\nAlice:医生：不是哦，是2

还有那怎么训练呢？从0开始训练可以吗？可以用下面的命令来训练吗？
cd /RWKV-LM/RWKV-v4
用 python train.py 可以训练上面的样式吗?

我只是想知道这个而已，之前在群问一会说不收费，没办法告知， 一说有文档，一会说没时间写文档叫我来写。我都写到这份都卡在这里，为什么，一会又说别人给你喂到嘴边， 我内心一万个XXXX,  我真是想上去......。   一会说自己解决， 从来不正面说事的，感觉内耗特别严重。


以后只是个人牢骚， 不代表我不支持作者， 当然我肯定希望 国内 框架越来越来， 生态越来越好！  同是也希望我的 的问题 能得到解决 ， 仅此而已~~~！！ 感谢！！
