### ISSUE TITLE
关于训练数据集

### ISSUE THREAD

**Issue by Galaxy-Ding** [BlinkDL/ChatRWKV#102]
你好作者：
感谢您的做出的工作，看了许多衍生出来仓库和许多的开源作品，真替您感到高兴。

背景：
我们准备接一个公司的机器人的对话，想试下您这边的模型开发。之后查阅了各个知乎文档，似乎没数据准备比较详细的资料，查阅资料1https://zhuanlan.zhihu.com/p/616351661， 资料2 https://zhuanlan.zhihu.com/p/616351661，

问题：

生产资料是对于厂来说是比较专业的知识，不能公开的。想做一个基于生产资料的问答机器人，但是我看了你的github仓库基本都是 一般的人机对话，或者小说的生成，若是想做一个垂直领域比较专业的机器人的话，那么需要做那些改变呢？

猜想：

```
{
	"context": 专业领域的资料背景知识内容。（可能一篇文章？长度比较长？）
	"question": 基于专业背景的知识问题,
	"answer": 基于上述的专业回答
}
```

期待您的回复

**Comment by BlinkDL** [comment]
Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

# Instruction:
基于专业背景的知识问题

# Input:
专业领域的资料背景知识内容

# Response:
基于上述的专业回答

**Comment by Galaxy-Ding** [comment]
{"meta": {"ID": 101}, "text": "This is the first document."} 

{"meta": {"ID": 102}, "text": "Hello\nWorld"} 

{"meta": {"ID": 103}, "text": "1+1=2\n1+2=3\n2+2=4"} 

代码如下

------------------------------------------------------------

ss = json.dumps({"meta": meta, "text": text}, ensure_ascii=False)
out.write(ss + "\n") 作者：czhko https://www.bilibili.com/read/cv22445881 出处：bilibili

**Comment by BlinkDL** [comment]
就是转成我前面写的格式，text 里面的内容是 ```
Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

# Instruction:
基于专业背景的知识问题

# Input:
专业领域的资料背景知识内容

# Response:
基于上述的专业回答
```

**Comment by Galaxy-Ding** [comment]
格式我是明白了，我想表达的意思是:
因为参考格式转换是
{"meta": {"ID": 101}, "text": "This is the first document."} 

{"meta": {"ID": 102}, "text": "Hello\nWorld"} 

{"meta": {"ID": 103}, "text": "1+1=2\n1+2=3\n2+2=4"} 
> 那么对应的转换脚本也是上述格式的转换脚本，但是我现在的转换脚本和他不一样。所以我就不知道对应的脚本是哪个可以参考？或者有那种格式是输出的，我自己应该怎么写

**Comment by gg22mm** [comment]
多轮对话呢，训练文档写得这么含糊的吗？

**Comment by gg22mm** [comment]
希望训练文档写一下具体点的..  包括多轮对话。  数据集样式 。谢谢..  到时候我再来玩~~

**Comment by BlinkDL** [comment]
@gg22mm 
```
Bob: xxxxxxxxxxxx

Alice: xxxxxxxx
xxxxxxxxxxx
xxxxxxxxxx

Bob: xxxxxxxxxxxxxxxx

Alice:
```

**Comment by gg22mm** [comment]
我试了一下：
Bob: 你叫什么名字?
Alice: 我叫小王女生，今年18岁，我正在读大一
Bob: 1+1=？
Alice:等于二
Bob: 不是3吗
Alice:不是哦，别搞错了
Bob: 好的谢
Alice:不用客气

cd /RWKV-LM/RWKV-v4
EXPRESS_PILE_MODE = False # True：微调 / False：常规训练(从0开始训练)
用 python train.py 报错了，是不格式还是不对吗？
![图片](https://github.com/BlinkDL/ChatRWKV/assets/6648329/b13707f0-cdea-438d-aae0-74c01eac0684)

**Comment by ysanimals** [comment]
有具体的jsonl的例子吗，感觉说的不是很明白  以及希望完善一下文档支持

**Comment by BlinkDL** [comment]
另外请阅读
https://zhuanlan.zhihu.com/p/638326262
https://zhuanlan.zhihu.com/p/639629050
