### ISSUE TITLE
Struggling to get your custom CUDA kernel to run

### ISSUE THREAD

**Issue by jojac47** [BlinkDL/ChatRWKV#103]

**Comment by jojac47** [comment]
Do you know if the Cuda kernel requires cuda 11.7 or is 12 ok as well?

**Comment by BlinkDL** [comment]
Hi I have only tested 11.7

**Comment by jojac47** [comment]
Thank you for the super quick response! I just tried to set up the demo with RWKV_CUDA set to 1 and it still errors out. I reinstalled cuda toolkit 11.7 and checked Visual Studio Intergration and reinstalled the cudda 11.7 torch combo in my conda environment after installing Visual Studio desktop with C++.  I installed all of the re requirements on the requirements.txt file on your gradio demo on Hugging Face.  Using [C:\Users\MYUSERACCT\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu117](file:///C:/Users/MYUSERACCT/AppData/Local/torch_extensions/torch_extensions/Cache/py39_cu117) as PyTorch extensions root...
[c:\Users\MYUSERACCT\Anaconda3\envs\RWKVEnv\lib\site-packages\torch\utils\cpp_extension.py:359](file:///C:/Users/MYUSERACCT/Anaconda3/envs/RWKVEnv/lib/site-packages/torch/utils/cpp_extension.py:359): UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Detected CUDA files, patching ldflags
Emitting ninja build file [C:\Users\MYUSERACCT\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu117\wkv_cuda\build.ninja...](file:///C:/Users/MYUSERACCT/AppData/Local/torch_extensions/torch_extensions/Cache/py39_cu117/wkv_cuda/build.ninja...)
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?edfebca3-b073-49b4-b767-4e946d7c3cd9)---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
Cell In[2], line 1
----> 1 from rwkv.model import RWKV
      2 from rwkv.utils import PIPELINE, PIPELINE_ARGS

File [c:\Users\MYUSERACCT\Anaconda3\envs\RWKVEnv\lib\site-packages\rwkv\model.py:29](file:///C:/Users/MYUSERACCT/Anaconda3/envs/RWKVEnv/lib/site-packages/rwkv/model.py:29)
     27 if os.environ.get('RWKV_CUDA_ON') == '1':
     28     from torch.utils.cpp_extension import load
---> 29     load(
     30         name=f"wkv_cuda",
     31         sources=[f"{current_path}/cuda/wrapper.cpp", f"{current_path}/cuda/operators.cu"],
     32         verbose=True,
     33         extra_cuda_cflags=["-t 4", "-std=c++17", "--use_fast_math", "-O3", "--extra-device-vectorization"],
     34         is_python_module=False)
     36     @MyStatic
     37     def cuda_wkv(T: int, C: int, w, u, k, v, aa, bb, pp):
     38         assert 1 * C % min(C, 32) == 0

File [c:\Users\MYUSERACCT\Anaconda3\envs\RWKVEnv\lib\site-packages\torch\utils\cpp_extension.py:1284](file:///C:/Users/MYUSERACCT/Anaconda3/envs/RWKVEnv/lib/site-packages/torch/utils/cpp_extension.py:1284), in load(name, sources, extra_cflags, extra_cuda_cflags, extra_ldflags, extra_include_paths, build_directory, verbose, with_cuda, is_python_module, is_standalone, keep_intermediates)
   1192 def load(name,
   1193          sources: Union[str, List[str]],
   1194          extra_cflags=None,
   (...)
   1202          is_standalone=False,
...
--> 528         raise CalledProcessError(retcode, process.args,
    529                                  output=stdout, stderr=stderr)
    530 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by BlinkDL** [comment]
from ChatRWKV readme:
```
### Note RWKV_CUDA_ON will build a CUDA kernel ("pip install ninja" first).
### How to build in Linux: set these and run v2/chat.py
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
### How to build in win:
Install VS2022 build tools (https://aka.ms/vs/17/release/vs_BuildTools.exe select Desktop C++). Reinstall CUDA 11.7 (install VC++ extensions). Run v2/chat.py in "x64 native tools command prompt". 
```
