### ISSUE TITLE
Keep saying "no CUDA", while installed Pytorch 2.0, with cuda11.7, on A100"

### ISSUE THREAD

**Issue by wensdong** [BlinkDL/ChatRWKV#11]
[/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py](https://localhost:8080/#) in _lazy_init()
    245         if 'CUDA_MODULE_LOADING' not in os.environ:
    246             os.environ['CUDA_MODULE_LOADING'] = 'LAZY'
--> 247         torch._C._cuda_init()
    248         # Some of the queued calls may reentrantly call _lazy_init();
    249         # we need to just return without initializing in that case.

RuntimeError: No CUDA GPUs are available

**Comment by wensdong** [comment]
The following is the full error mesaage:

"ChatRWKV project: https://github.com/BlinkDL/ChatRWKV

Loading ChatRWKV - English - cuda - fp16 - QA_PROMPT False

RWKV_JIT_ON 1

Loading model - /content/ChatRWKV/rwkv-4-pile-169m/RWKV-4-Pile-169M-20220807-8023
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-20-0478305d1ec7>](https://localhost:8080/#) in <module>
    197 
    198 print(f'Loading model - {MODEL_NAME}')
--> 199 model = RWKV_RNN(args)
    200 
    201 model_tokens = []

2 frames
[/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py](https://localhost:8080/#) in _lazy_init()
    245         if 'CUDA_MODULE_LOADING' not in os.environ:
    246             os.environ['CUDA_MODULE_LOADING'] = 'LAZY'
--> 247         torch._C._cuda_init()
    248         # Some of the queued calls may reentrantly call _lazy_init();
    249         # we need to just return without initializing in that case.

RuntimeError: No CUDA GPUs are available"

**Comment by BlinkDL** [comment]
pip install torch --extra-index-url https://download.pytorch.org/whl/cu117
Make sure you install torch 1.13.1+cu117

**Comment by wensdong** [comment]
After a little back and forth, it worked. Thanks so much!
