### ISSUE TITLE
Inference time for different strategy fp16 and fp16i8

### ISSUE THREAD

**Issue by fubincom** [BlinkDL/ChatRWKV#114]
Hello, I download the model RWKV-4-Raven-7B-v11x-Eng99%-Other1%-20230429-ctx8192.pth and convert it to the fp16 and fp16i8 versions following the introduction. And I also exported the envs variables RWKV_CUDA_ON=1 when I convert the model. But when I test it in benchmark.py on LAMBADA test set, the inference time of fp16i8 version is too slower than the fp16 version. For 100 samples, fp16 only need 4s and fp16i8 need 145s. Is it normal or did I miss something? 

I didn't use other hyperparameters for fp16i8 version like fp16i8 *n+.

My GPU is V100, CUDA version is 118, sorry I can't change to 117.

Any response is appreciated

**Comment by BlinkDL** [comment]
Seems you are not really using the CUDA kernel
fp16i8 + cuda is faster than fp16

**Comment by fubincom** [comment]
> Seems you are not really using the CUDA kernel fp16i8 + cuda is faster than fp16

But when I load the model, they. told me the weight were int8 using cuda:0... not sure. But I have tried the model in inference, the time is acceptable...

**Comment by BlinkDL** [comment]
"cuda:0" means it's using cuda
but it's not using the much faster custom cuda kernel

**Comment by fubincom** [comment]
Maybe you're correct. I can't reinstall the cuda since I use a docker. I have tried to do it but versions always have some issue.... Thanks your response
