### ISSUE TITLE
readme寫的不清楚

### ISSUE THREAD

**Issue by zzzgit** [BlinkDL/ChatRWKV#116]
hi
readme可以再詳細一點嗎？
如何install，如何運行，完全不懂。。。

**Comment by BlinkDL** [comment]
可以加QQ群 818930736
可以看知乎：https://zhuanlan.zhihu.com/p/626083366

**Comment by BlinkDL** [comment]
另外请阅读
https://zhuanlan.zhihu.com/p/638326262
https://zhuanlan.zhihu.com/p/639629050
