### ISSUE TITLE
干货训练多轮对话系统文档

### ISSUE THREAD

**Issue by gg22mm** [BlinkDL/ChatRWKV#118]
参考自：
https://github.com/BlinkDL/ChatRWKV/issues/102
https://github.com/BlinkDL/RWKV-LM/issues/118

首选感谢作者，开发了这么好的框架！  并开源， 必须支持一播，希望生态越来越好，好的环境从我做起 ！  奥利给~~。  

cd /RWKV-LM

1、数据集
mkdir  data
vi ./data/train.txt内容如下

Bob: 你叫什么名字?
Alice: 我叫小王，女生，今年18岁，我正在读大一
Bob: 1+1=？
Alice:等于二
Bob: 不是3吗
Alice:不是哦，别搞错了
Bob: 好的谢
Alice:不用客气

2、训练
     
cd ./RWKV-v4
vi train.py

// 默认使用的数据集合
datafile = "../data/train.txt" 
datafile_encoding = 'utf-8' 
EXPRESS_PILE_MODE = False # True：微调 / False：常规训练(从0开始训练)

3、加载训练模型

加载要用：  https://github.com/BlinkDL/RWKV-LM/blob/main/RWKV-v4/run.py 
为什么不能用：https://github.com/BlinkDL/ChatRWKV/blob/main/chat.py  ，因为tokenizer我自己的，所以只能用上面的方式，如果非要用那么数据集必须是：20B_tokenizer.json 生成的样式

**Comment by fubincom** [comment]
请问下，你这个多轮对话的数据集，需要也放入text字段吗？

**Comment by gg22mm** [comment]
> 下，你这个多轮对话的数据集，需要也放入text字段吗？

多轮是这种格式：
{"text": "\nBob: 1+1=?\n\nAlice: 1+1=2\n"}#一段对话结束
{"text": "\nBob: 2+2=?\n\nAlice: 等于4\n\nBob: 不是8吗？\n\nAlice: 不是8是4，就搞错了\n\nBob: 好的谢谢\n\nAlice: 不客气\n"} #一段对话结束

**Comment by fubincom** [comment]
-- my_pile_stage 设置成1 可以直接复用 Author的配置也不错，要不然我们自己瞎给一个我不是很清楚什么意思

**Comment by gg22mm** [comment]
前 \n 是必须的，说是这样的，具体我到是没试过。  还有本来就是不会训练停止的，需要人工手动停止。 其它参数看上面的文档

**Comment by fubincom** [comment]
好的，谢谢。train.py 里面有args.max_epochs = -1 没有放到 argparser里面，但是trainer初始化的时候也会用到，这个是不会停止的原因。所以在脚本里面把-1改成你想要的epoch就可以了。
- ctx_len 我不太清楚是否和显存有关系，论文里面是没有关系的 https://arxiv.org/pdf/2305.13048.pdf  Space: O(d)

**Comment by fubincom** [comment]
@gg22mm 我问下您训练以后得到的对话是否正常，我这边得到的对话，总是会把Alice 以及 不同行的语料一起加入到回复，我不知道是不是dataloader 里面都没有提取

Alice:The intent title is XXX？As a customer, I hope this information helps you understand it", "meta": {"ID": "3866"}}
{"text": "\nBob: hi 。。。。。
这个是整个response，感觉就是把我的训练语料全吃进去，并没有提text，所以生成的时候什么都有 不知道你有没有这个问题，以及怎么解决的

**Comment by BlinkDL** [comment]
另外请阅读
https://zhuanlan.zhihu.com/p/638326262
https://zhuanlan.zhihu.com/p/639629050
