### ISSUE TITLE
Can TensorRT be used to further accelerate the inference speed of ChatRWKV?

### ISSUE THREAD

**Issue by Pevernow** [BlinkDL/ChatRWKV#124]
TensorRT has a performance advantage of over 2.5 times compared to Pytorch backend running on Cuda on certain devices.

Is there a plan to add this feature to ChatRWKV to further reduce the hardware entry requirements for large language models?

**Comment by BlinkDL** [comment]
You are welcome to raise this issue in https://github.com/harrisonvanderbyl/rwkv-cpp-cuda
