### ISSUE TITLE
输出乱码

### ISSUE THREAD

**Issue by onexuan** [BlinkDL/ChatRWKV#127]
<img width="1231" alt="截屏2023-05-24 17 01 02" src="https://github.com/BlinkDL/ChatRWKV/assets/2910709/51642c91-6989-4816-bea2-386d4d92efb7">

**Comment by BlinkDL** [comment]
你好，你的解码参数是完全错误的！topp 推荐 0.5

而且中文问题需要用中文模型，各个模型的地址： https://www.zhihu.com/question/602564718/answer/3042600470
