### ISSUE TITLE
请教关于用custom dataset 微调后的遗忘问题

### ISSUE THREAD

**Issue by valkryhx** [BlinkDL/ChatRWKV#128]
大佬好  今天刚看到rwkv这个分支的llm 很感兴趣 想请教一下这个模型是否也存在和transformer类模型类似的finetune后灾难性遗忘问题 ？即预训练好的模型经过本地特定语料finetune后 虽然在特定领域qa效果还行 但原先的生成能力变得很弱。谢谢。

**Comment by valkryhx** [comment]
如果rwkv也有这个catastrophic forgetting问题的话 您是否有好的finetune建议

**Comment by BlinkDL** [comment]
您好，在finetune语料随机混入一些基础语料，即可保持基础语料的能力
