### ISSUE TITLE
好混乱啊

### ISSUE THREAD

**Issue by thelongestusernameofall** [BlinkDL/ChatRWKV#131]
参考一下vicuna、alpaca-lora的项目组织啊。

这个项目怎么感觉好混乱。一直在循环反复的提供混杂而相互重叠的信息。

但如何快速部署、快速阅读，却帮助不大

**Comment by BlinkDL** [comment]
可以看 http://rwkv.com/

**Comment by BlinkDL** [comment]
另外请阅读：
https://zhuanlan.zhihu.com/p/638326262
https://zhuanlan.zhihu.com/p/639629050
