### ISSUE TITLE
pb with tokeniser

### ISSUE THREAD

**Issue by bello7777** [BlinkDL/ChatRWKV#132]
I tried to run from scratch the rwkn-4neo, I used my token vocab.json created , it still give me that error, I tried eveything , changed token nothing  any hinch pls

Traceback (most recent call last):
  File "/home/ubuntu/chatrwkv/chat.py", line 83, in <module>
    tokenizer = TOKENIZER("/home/ubuntu/RWKV-v4neo/out/out/vocab_new.json")
  File "/home/ubuntu/chatrwkv/src/utils.py", line 23, in __init__
    self.tokenizer = Tokenizer.from_file(WORD_NAME)
Exception: key must be a string at line 1 column 2

**Comment by BlinkDL** [comment]
use https://github.com/BlinkDL/RWKV-LM/blob/main/RWKV-v4/run.py to run your train-from-scratch model
