### ISSUE TITLE
[Q] End-of-text token disabled

### ISSUE THREAD

**Issue by ellonde** [BlinkDL/ChatRWKV#138]
Hello there. Thanks a bunch for the great work on this model. Its super cool! I just have a quick question and I wasn't able to find any other resources on this.

In the chat the endoftext token(0) is disabled and the chat flow seems to be controlled with newlines instead. Why is that? Is it just because thats how you have constructed the prompts or is there a more fundamental reasoning behind it?

Thanks again :)

**Comment by l15y** [comment]
May be you are useing RWKV?
In RWKV,model only output \n\n ,because token(0) is not used during training.

**Comment by BlinkDL** [comment]
[0] is used to separate documents

**Comment by ellonde** [comment]
That makes sense. Thanks 👍
