### ISSUE TITLE
Not enough memory for 1 gpu

### ISSUE THREAD

**Issue by xiongsp** [BlinkDL/ChatRWKV#14]
There are 2 gpus on my PC but the model can't be loaded on both of them, thus it can't run 14B model. Here are some information.
```bash
Traceback (most recent call last):
  File "chat.py", line 199, in <module>
    model = RWKV_RNN(args)
  File "/home/*/ChatRWKV/lib/python3.8/site-packages/torch/jit/_script.py", line 293, in init_then_script
    original_init(self, *args, **kwargs)
  File "/home/*/ChatRWKV/src/model_run.py", line 76, in __init__
    w[x] = w[x].cuda()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 23.69 GiB total capacity; 19.19 GiB already allocated; 39.12 MiB free; 19.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

So, is it possible to use both of my gpus? Thanks!

**Comment by HaishengLiang** [comment]
3B model need 6GiB GPU memory or more. 
7B model need 14GiB GPU memory or more. 
14B model need 28GiB GPU memory or more. 
Or you can run it with CPU by 128G memory limit. 

reasoning of multiple graphics cards has not been implemented yet
you can use DeepSpeed for multiple graphics cards train

**Comment by HaishengLiang** [comment]
May be you can run model with 8bit not for bf16 
it should be use less GPU memory.

**Comment by xiongsp** [comment]
Thanks. By the way, do you plan to implement reasoning of multiple graphics cards?

**Comment by BlinkDL** [comment]
Run Single Model on Multiple GPUs:
https://github.com/BlinkDL/ChatRWKV/pull/12
https://github.com/mpskex/ChatRWKV

**Comment by xiongsp** [comment]
I see. Thanks!
