### ISSUE TITLE
Problem with downloading model weights

### ISSUE THREAD

**Issue by StarDewXXX** [BlinkDL/ChatRWKV#141]
[](url)
![image](https://github.com/BlinkDL/ChatRWKV/assets/53181512/b4e196f5-5ba6-4455-a380-bf0cc57174bf)

When I run v2/benchmark_world.py, got this:
FileNotFoundError: [Errno 2] No such file or directory: '/fsx/BlinkDL/HF-MODEL/rwkv-4-world/RWKV-4-World-0.1B-v1-20230520-ctx4096.pth'

**Comment by BlinkDL** [comment]
download here: https://huggingface.co/BlinkDL/rwkv-4-world
