### ISSUE TITLE
cpu运算乱码问题

### ISSUE THREAD

**Issue by lmsdscav** [BlinkDL/ChatRWKV#149]
Bob: hi
Alice: willepicReferences**z ntateh

模型RWKV-4-World-1.5B-v1-fixed-20230612-ctx4096.pth
环境ubuntu
cpu mode
fp32

**Comment by BlinkDL** [comment]
world要改词表，方法写在了https://huggingface.co/BlinkDL/rwkv-4-world

如果不懂就用 https://github.com/josStorer/RWKV-Runner/releases
