### ISSUE TITLE
demo ?

### ISSUE THREAD

**Issue by malv-c** [BlinkDL/ChatRWKV#164]

**Comment by malv-c** [comment]
% pip show rwkv
Name: rwkv
Version: 0.8.9
Summary: The RWKV Language Model
Home-page:
Author: Bo PENG
Author-email:
License:
Location: /M/conda/envs/lcpu/lib/python3.11/site-packages
Requires: tokenizers
Required-by:
(lcpu) /M/rwkv-cpp-accelerated
% python *y
Traceback (most recent call last):
  File "/M/rwkv-cpp-accelerated/RWKV_v5_demo.py", line 106, in <module>
    tokenizer = RWKV_TOKENIZER("tokenizer/rwkv_vocab_v20230424.txt")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/M/rwkv-cpp-accelerated/RWKV_v5_demo.py", line 21, in __init__
    lines = open(file_name, "r", encoding="utf-8").readlines()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'tokenizer/rwkv_vocab_v20230424.txt'

**Comment by BlinkDL** [comment]
use absolute path of rwkv_vocab_v20230424.txt
