### ISSUE TITLE
huggingface无法访问，模型无法下载

### ISSUE THREAD

**Issue by xiaokai-lyk** [BlinkDL/ChatRWKV#169]
由于法律法规的原因，中国大陆地区无法访问 huggingface 同理，RWKV-Runner的模型下载功能 也无法使用，请问有什么解决办法吗？而且模型下载消耗的流量太多，无法使用魔法上网（成本无法控制）

**Comment by PJ-568** [comment]
Cloudflare 或 Vercel 反代。但严禁滥用。

**Comment by xiaokai-lyk** [comment]
好的我试试

**Comment by PJ-568** [comment]
附加：可以去[魔搭](https://www.modelscope.cn/)的仓库的库拉取模型，详见[文档](https://www.modelscope.cn/docs/%E6%A8%A1%E5%9E%8B%E7%9A%84%E4%B8%8B%E8%BD%BD)。

**Comment by xiaokai-lyk** [comment]
> 附加：可以去[魔搭](https://www.modelscope.cn/)的仓库的库拉取模型，详见[文档](https://www.modelscope.cn/docs/%E6%A8%A1%E5%9E%8B%E7%9A%84%E4%B8%8B%E8%BD%BD#%E4%BD%BF%E7%94%A8Git%E4%B8%8B%E8%BD%BD%E6%A8%A1%E5%9E%8B)。

这种方法看上去更简单，我试一下(反向代理对分发不太友好)
