### ISSUE TITLE
Still OOM for v2

### ISSUE THREAD

**Issue by kizunasunhy** [BlinkDL/ChatRWKV#21]
Tried the v2 chat.py with the 14B model but still got OOM for the 24GB graphics memory. 
Torch version is 13.0. Why?

**Comment by BlinkDL** [comment]
edit args.strategy. try 'cuda fp16 *30 -> cpu fp32' first. increase 30 for more speedup (and more VRAM consumption).

**Comment by kizunasunhy** [comment]
> edit args.strategy in chat.py. try 'cuda fp16 *30 -> cpu fp32' first. increase 30 for more speedup (and more VRAM consumption).


Got it!
