### ISSUE TITLE
lowering temperature in chat.py leads to error.

### ISSUE THREAD

**Issue by dbddv01** [BlinkDL/ChatRWKV#22]
In v2, chat.py, when trying to lower the temperature under its 1.0 default,  for example  GEN_TEMP = 0.9
I'm faced with 

File "chat.py", line 393, in <module>
    on_message(msg)
  File "chat.py", line 300, in on_message
    token = pipeline.sample_logits(
  File "(...)\utils.py", line 51, in sample_logits
    probs = probs.pow(1.0 / temperature)
AttributeError: 'numpy.ndarray' object has no attribute 'pow'

Just that you know.

**Comment by BlinkDL** [comment]
fixed :)
