### ISSUE TITLE
No time_shift use in ChatRWKV?

### ISSUE THREAD

**Issue by 3outeille** [BlinkDL/ChatRWKV#27]
Hi,

Why is `time_shift` not applied in ChatRWKV on `x` before computing [`x * self.time_mix_k + xx * (1 - self.time_mix_k)`](https://github.com/BlinkDL/ChatRWKV/blob/main/RWKV_in_150_lines.py#L68) while in RWKV V4, [it is the case](https://github.com/BlinkDL/RWKV-LM/blob/main/RWKV-v4/src/model_run.py#L136). Any idea ?

**Comment by Blealtan** [comment]
`state[5*i+1]` is the `x` in previous iteration, see [here](https://github.com/BlinkDL/ChatRWKV/blob/73aa9e04eb98609243f6be20c53d0b64b659aa8d/RWKV_in_150_lines.py#L71). It's exactly what `time_shift` do.
