### ISSUE TITLE
setup of ChatRWKV

### ISSUE THREAD

**Issue by bello7777** [BlinkDL/ChatRWKV#29]
Hey guys great stuff, can we have very easy setup step process  to install ChatRWKV on a ubuntu server for example?

**Comment by soulteary** [comment]
There is no need to toss the environment, just use the container @bello7777 

https://github.com/BlinkDL/ChatRWKV/pull/58

**Comment by bello7777** [comment]
Thanks mate, I will do it .
 for the moment I just launch it on AWS ubuntu 18.04 , I'm dealing with DefaultCPUAllocator as 
I can't allocate enough memory on the server

**Comment by bello7777** [comment]
@soulteary 
i tried to access your blog and guidelines but i could not, 
could you give me the steps and version of Docker container so i can deploy it on ec2 server as a still have a problem with memory

**Comment by KerfuffleV2** [comment]
@bello7777 You probably need to adjust the strategy. If you're using the pull request:

```python3
    model = RWKV(model=model_path, strategy='cuda fp16i8 *20 -> cuda fp16')
```

That's around line 28 in `webui.py` from that pull. You didn't say what you're actually doing, so there's no way to know if you're saying it failed when trying to load the model for inference, when converting, whatever.

But the most likely solution is to find whatever is running and how it's setting the strategy and reduce the number of layers it will send to the GPU. For example, in the line above you could try using `cuda fp16i8 *10 -> cuda fp16` instead which should roughly half the required GPU memory.

After you get it going, you can use other tools to see how much GPU memory you have available and adjust the setting according.

**Comment by bello7777** [comment]
thanks solved and working 
![trstchat](https://user-images.githubusercontent.com/73637239/228835338-b415f08f-619c-4359-8593-f36dee86123c.jpg)
now moving to train the model

**Comment by bello7777** [comment]
Last question here, when I want to stop the chat , what should i say or do to stop it ?
