### ISSUE TITLE
Remove pytorch dependency

### ISSUE THREAD

**Issue by oobabooga** [BlinkDL/ChatRWKV#46]
The RWKV package includes a 

```
  'torch ~= 1.13.1',
```

dependency. In cases where pytorch is installed using conda (a very common case) or some other means, this causes a conflict. 

Most machine learning libraries do not include pytorch as a requirement.

Is it possible to remove this dependency?

**Comment by BlinkDL** [comment]
ok i will remove it

**Comment by BlinkDL** [comment]
use 0.6.1
