### ISSUE TITLE
RuntimeError: default_program(57): error: identifier "aten_add_flat__1" is undefined

### ISSUE THREAD

**Issue by xinghua3632** [BlinkDL/ChatRWKV#54]
I download and use RWKV-4-Pile-3B-20221110-ctx4096.bin to test(python chat.py), but there are errors:
Run prompt...
Traceback (most recent call last):
  File "chat.py", line 167, in <module>
    out = run_rnn(pipeline.encode(init_prompt))
  File "chat.py", line 136, in run_rnn
    out, model_state = model.forward(tokens[:CHUNK_LEN], model_state)
  File "/data/home/clarkjiang/ChatRWKV-main/v2/../rwkv_pip_package/src/rwkv/model.py", line 616, in forward
    omx, orx, omy, ory,
RuntimeError: default_program(57): error: identifier "aten_add_flat__1" is undefined

default_program(58): error: no operator "=" matches these operands
            operand types are: half = float

2 errors detected in the compilation of "default_program".

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

#define __HALF_TO_US(var) *(reinterpret_cast<unsigned short *>(&(var)))
#define __HALF_TO_CUS(var) *(reinterpret_cast<const unsigned short *>(&(var)))
#if defined(__cplusplus)
  struct __align__(2) __half {
    __host__ __device__ __half() { }

  protected:
    unsigned short __x;
  };

  /* All intrinsic functions are only available to nvcc compilers */
  #if defined(__CUDACC__)
    /* Definitions of intrinsics */
    __device__ __half __float2half(const float f) {
      __half val;
      asm("{  cvt.rn.f16.f32 %0, %1;}\n" : "=h"(__HALF_TO_US(val)) : "f"(f));
      return val;
    }

    __device__ float __half2float(const __half h) {
      float val;
      asm("{  cvt.f32.f16 %0, %1;}\n" : "=f"(val) : "h"(__HALF_TO_CUS(h)));
      return val;
    }

  #endif /* defined(__CUDACC__) */
#endif /* defined(__cplusplus) */
#undef __HALF_TO_US
#undef __HALF_TO_CUS

typedef __half half;

extern "C" __global__
void func_1(half* t0, half* t1, half* t2, half* t3, half* t4, half* t5, half* aten_add_flat, half* aten_add_flat_1, half* aten_add_flat_2, half* aten_cat_flat) {
{
  aten_cat_flat[512 * blockIdx.x + threadIdx.x] = __float2half((((512 * blockIdx.x + threadIdx.x) / 2560<1 ? 1 : 0) ? __half2float(t5[(512 * blockIdx.x + threadIdx.x) % 2560]) : __half2float(t4[(512 * blockIdx.x + threadIdx.x) - 2560])));
  float t1_ = __half2float(t1[512 * blockIdx.x + threadIdx.x]);
  float aten_add_flat_ = __half2float(aten_add_flat[512 * blockIdx.x + threadIdx.x]);
  float t0_ = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 2560]);
  aten_add_flat__1 = __float2half(t1_ * t0_ + ((((512 * blockIdx.x + threadIdx.x) / 2560<1 ? 1 : 0) ? __half2float(t5[(512 * blockIdx.x + threadIdx.x) % 2560]) : __half2float(t4[(512 * blockIdx.x + threadIdx.x) - 2560]))) * ((0.f - t0_) + 1.f));
  aten_add_flat[512 * blockIdx.x + threadIdx.x] = aten_add_flat_;
  float t2_ = __half2float(t2[(512 * blockIdx.x + threadIdx.x) % 2560]);
  aten_add_flat_1[512 * blockIdx.x + threadIdx.x] = __float2half(t1_ * t2_ + ((((512 * blockIdx.x + threadIdx.x) / 2560<1 ? 1 : 0) ? __half2float(t5[(512 * blockIdx.x + threadIdx.x) % 2560]) : __half2float(t4[(512 * blockIdx.x + threadIdx.x) - 2560]))) * ((0.f - t2_) + 1.f));
  float t3_ = __half2float(t3[(512 * blockIdx.x + threadIdx.x) % 2560]);
  aten_add_flat_2[512 * blockIdx.x + threadIdx.x] = __float2half(t1_ * t3_ + ((((512 * blockIdx.x + threadIdx.x) / 2560<1 ? 1 : 0) ? __half2float(t5[(512 * blockIdx.x + threadIdx.x) % 2560]) : __half2float(t4[(512 * blockIdx.x + threadIdx.x) - 2560]))) * ((0.f - t3_) + 1.f));
}
}

what is wrong?

**Comment by BlinkDL** [comment]
try torch 1.13.1+cu117 and cuda 11.7
