### ISSUE TITLE
v2 models

### ISSUE THREAD

**Issue by loretoparisi** [BlinkDL/ChatRWKV#56]
Hello, since I'm running in VRAM constraints I would like to start using v2.
I have seen in the `v2/` folder a conversion script. Do I need to convert a RWKV model [like](https://huggingface.co/BlinkDL/rwkv-4-pile-7b) before using it in v2?

**Comment by BlinkDL** [comment]
Conversion can save CPU RAM while loading.
Use "strategy" to save VRAM: https://pypi.org/project/rwkv/
