### ISSUE TITLE
Hi any example of conversation ?

### ISSUE THREAD

**Issue by djaffer** [BlinkDL/ChatRWKV#66]
Hi do you have any examples of where it is conversational? I am trying to find the best way to send conversational history.
 
 Right now, the answer is too long. 
 
 
![image](https://user-images.githubusercontent.com/5740725/228522258-2506eb02-1c17-4ff8-850a-1a370354f87a.png)

**Comment by BlinkDL** [comment]
Run https://github.com/BlinkDL/ChatRWKV/blob/main/v2/chat.py and it's conversational.
