### ISSUE TITLE
Improve code/instruction for how to download model fsx/BlinkDL/HF-MODEL

### ISSUE THREAD

**Issue by djaffer** [BlinkDL/ChatRWKV#69]
Clarify that so it is easier to follow.

Was getting this error 

FileNotFoundError: [Errno 2] No such file or directory: '/fsx/BlinkDL/HF-MODEL/rwkv-4-pile-14b/RWKV-4-Pile-14B-20230313-ctx8192-test1050.pth'

```
title = "RWKV-4-Pile-14B-20230313-ctx8192-test1050"
model_path = hf_hub_download(repo_id="BlinkDL/rwkv-4-pile-14b", filename=f"{title}.pth")
model = RWKV(model=model_path, strategy='cpu')

```

**Comment by BlinkDL** [comment]
seems you are still loading model from the default path
make sure you are editing v2/chat.py and running v2/chat.py
