### ISSUE TITLE
 "LayerNormKernelImpl" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by wangshankun** [BlinkDL/ChatRWKV#7]
Version:
![image](https://user-images.githubusercontent.com/3970271/217139913-14fa0e7f-d49a-46b7-af34-cc2ef7aa1bff.png)

Loading model :
RWKV-4-Pile-7B-Instruct-test1-20230124

Error:
 Traceback (most recent call last):
  File "chat.py", line 175, in <module>
    model = RWKV_RNN(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_script.py", line 272, in init_then_script
    original_init(self, *args, **kwargs)
  File "/root/work/ChatRWKV/src/model_run.py", line 103, in __init__
    x = self.LN(self.w.emb.weight, self.w.blocks[0].ln0)
  File "/root/work/ChatRWKV/src/model_run.py", line 111, in LN
    return F.layer_norm(x, (self.args.n_embd,), weight=w.weight, bias=w.bias)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2346, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'BFloat16'

**Comment by BlinkDL** [comment]
Your GPU does not support bf16.  Use fp16.

**Comment by cxj01** [comment]
I had the same problem. How did you solve it?

**Comment by BlinkDL** [comment]
Please try latest version.

**Comment by cxgreat2014** [comment]
cpu模式，6G模型：
```log
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```

**Comment by BlinkDL** [comment]
> cpu模式，6G模型：
> 
> ```
> RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
> ```

fp16 (good for GPU, does NOT support CPU) // fp32 (good for CPU) // bf16 (worse accuracy, supports CPU)
