### ISSUE TITLE
Maximum Token Length

### ISSUE THREAD

**Issue by bitnom** [BlinkDL/ChatRWKV#71]
Just wondering what is token window/max token length? And your thoughts on increasing it?

---
ps: this repo is amazing. I wish I would have known about it sooner. you guys are awesome and I'll try to contrib at some point if I can.

**Comment by BlinkDL** [comment]
There are ctx8192 models (such as https://huggingface.co/BlinkDL/rwkv-4-pile-14b/blob/main/RWKV-4-Pile-14B-20230313-ctx8192-test1050.pth)

It's only limited by my bad training code :)
