### ISSUE TITLE
Simplify v2/Chat.py

### ISSUE THREAD

**Issue by djaffer** [BlinkDL/ChatRWKV#73]
Can you simplify chat.py so it is easier to follow and be used as an inference where history can be sent? Right, it seems pretty obfuscated where it using some hacks to limit output?

**Comment by BlinkDL** [comment]
My code is a horrible mess (too busy to refactor)

You can use RWKV pip package: https://pypi.org/project/rwkv/ to write your own version from scratch

**Comment by djaffer** [comment]
![image](https://user-images.githubusercontent.com/5740725/229337014-00744c8f-0de1-47a4-98d3-6d9d78bc06ac.png)

Getting error after converting the model.

**Comment by BlinkDL** [comment]
Make sure you are using latest rwkv (0.7.2)
pip install rwkv --upgrade

**Comment by KerfuffleV2** [comment]
> My code is a horrible mess (too busy to refactor)

Just checking. You're still not interested in letting someone else clean it up. Correct?

(Mostly talking about the actual model, not the chat example.)

**Comment by BlinkDL** [comment]
> Just checking. You're still not interested in letting someone else clean it up. Correct?
> (Mostly talking about the actual model, not the chat example.)

Please feel free to fork and write a better version :)

I will clean it when I am less busy (now training lots of models everyday)

**Comment by KerfuffleV2** [comment]
I'd be willing to do that, but it's something that would be a significant amount of work. So it basically would only be worth putting the time into if there was a pretty good chance of the changes getting accepted. 

Obviously it wouldn't be reasonable to expect you to promise to merge a pull request before even seeing it, but there's still a way to find out of something is generally the kind of change you're looking for/would accept. You can see my previous pull #47 for the type of changes I'm talking about.

**Comment by BlinkDL** [comment]
> I'd be willing to do that, but it's something that would be a significant amount of work. So it basically would only be worth putting the time into if there was a pretty good chance of the changes getting accepted.

Yeah I wont merge such large changes, but it will be great for understanding how the chat mode works, if you are interested :)

The best way to understand something is to write your own version

**Comment by KerfuffleV2** [comment]
> Yeah I wont merge such large changes

Fair enough. I think at some point you're going to have to clean up the code and it's going to be more difficult the larger and more complicated it becomes. Your choice though.

> The best way to understand something is to write your own version.

I actually already did. I wrote a Rust based implementation here: https://github.com/KerfuffleV2/smolrsrwkv

It's CPU only and actually runs about as fast as ChatRWKV in `cpu fp32` and `cpu fp32i8` mode.

If you think it could help other people in the community, please feel free to link it if you want to. (Also, I'd be happy to receive any constructive criticism about it.)
