### ISSUE TITLE
[a disappointing badcase on online demo] 

### ISSUE THREAD

**Issue by SrWYG** [BlinkDL/ChatRWKV#88]
首先想表达我对你们工作的敬意和惊叹。
我认为微调了attention free transformer的公式，以便能够动归计算来优化时间复杂度的做法非常有趣和实用。
但是在我想把你们的工作分享给更多的人，我去玩在线demo测试的时候。在一个case中，我直接使用了你们提供的prompt以及参数，但是这个case表现出的效果非常不好。
![image](https://user-images.githubusercontent.com/9276709/230734950-d4878425-556b-4a2f-b38f-143ef989d96d.png)
这个case会让我觉得，要么是【训练语料的混乱程度】要么是 【训练过程/方法本身 导致 对于结束状态判断的不是很好】
希望你们变得更好！

**Comment by SrWYG** [comment]
RWKV-4-Pile-14B-20230313-ctx8192-test1050

**Comment by pootow** [comment]
这个模型的上下文非常弱，几乎每隔一行就会完全忘记上一行的重点。但是还是鼓励一下作者。

**Comment by BlinkDL** [comment]
这并不是 bad case，而是我在 14B 模型故意允许这样。你应该测试 https://huggingface.co/spaces/BlinkDL/Raven-RWKV-7B 。

@pootow 你的模型用错了。看 https://zhuanlan.zhihu.com/p/619721229
