### ISSUE TITLE
update of rwkv error

### ISSUE THREAD

**Issue by bello7777** [BlinkDL/ChatRWKV#89]
When you updated the package rwkv 0.7.3  i started to get the following error that I m not able to fix when running the chat.py of V2

^C
CondaError: KeyboardInterrupt

(pytorch_p39) ubuntu@ip-172-31-26-101:~/chat/v2$ conda env torch
usage: conda-env [-h] {create,export,list,remove,update,config} ...
conda-env: error: argument {create,export,list,remove,update,config}: invalid choice: 'torch' (choose from 'create', 'export', 'list', 'remove', 'update', 'config')
(pytorch_p39) ubuntu@ip-172-31-26-101:~/chat/v2$ conda env lsit
usage: conda-env [-h] {create,export,list,remove,update,config} ...
conda-env: error: argument {create,export,list,remove,update,config}: invalid choice: 'lsit' (choose from 'create', 'export', 'list', 'remove', 'update', 'config')
(pytorch_p39) ubuntu@ip-172-31-26-101:~/chat/v2$ conda activate aws_neuron_pytorch_p37
(aws_neuron_pytorch_p37) ubuntu@ip-172-31-26-101:~/chat/v2$ python chat.py

ChatRWKV v2 https://github.com/BlinkDL/ChatRWKV

English - cuda fp16i8 -> cpu fp32 *10 - /home/ubuntu/chat/v2/prompt/default/English-2.py
Loading model - trained-500-141-1024-RWKV-6-512-2023-04-08-13-57-32
RWKV_JIT_ON 1 RWKV_CUDA_ON 0 RESCALE_LAYER 6

Loading trained-500-141-1024-RWKV-6-512-2023-04-08-13-57-32.pth ...
Strategy: (total 6+1=7 layers)
* cuda [float16, uint8], store 0 layers
* cpu [float32, float32], store 7 layers
0-cpu-float32-float32 1-cpu-float32-float32 2-cpu-float32-float32 3-cpu-float32-float32 4-cpu-float32-float32 5-cpu-float32-float32 6-cpu-float32-float32
Traceback (most recent call last):
  File "/home/ubuntu/chat/v2/../rwkv_pip_package/src/rwkv/model.py", line 196, in __init__
    w['emb.weight'] = F.layer_norm(w['emb.weight'], (args.n_embd,), weight=w['blocks.0.ln0.weight'], bias=w['blocks.0.ln0.bias'])
KeyError: 'blocks.0.ln0.weight'

**Comment by BlinkDL** [comment]
Are you using your own model trained from scratch? It will not be compatible with ChatRWKV unless you change some code.

**Comment by bello7777** [comment]
ahh yes I have trained the model using RWKV-LM got a pth file and just upload the file and run it for chatrwkv/v2 
so what i need to change  pls?
