### ISSUE TITLE
ModuleNotFoundError: No module named 'tokenizers.tokenizers'

### ISSUE THREAD

**Issue by LouisYYC** [BlinkDL/ChatRWKV#90]
When initiating the chatbot following error occurs:

Traceback (most recent call last):
  File "C:\Users\yongy\chatrwkv\v2\chat.py", line 125, in <module>
    pipeline = PIPELINE(model, f"{current_path}/20B_tokenizer.json")
  File "c:\users\yongy\appdata\local\programs\python\python37\lib\site-packages\rwkv\utils.py", line 28, in __init__
    from tokenizers import Tokenizer
  File "c:\users\yongy\appdata\local\programs\python\python37\lib\site-packages\tokenizers\__init__.py", line 80, in <module>
    from .tokenizers import (
ModuleNotFoundError: No module named 'tokenizers.tokenizers'

**Comment by BlinkDL** [comment]
pip install tokenizers --upgrade

**Comment by LouisYYC** [comment]
tried that, does not work

> pip install tokenizers --upgrade

**Comment by LouisYYC** [comment]
> pip install tokenizers --upgrade

tried that, does not work

 pip install tokenizers --upgrade
Requirement already satisfied: tokenizers in c:\users\yongy\appdata\local\programs\python\python37\lib\site-packages (0.13.3)

**Comment by BlinkDL** [comment]
you have multiple python on your system. check which python you are calling, and install package for it.

**Comment by BlinkDL** [comment]
and use python 3.10

**Comment by LouisYYC** [comment]
> use python 3.10

Already using python 3.10, has redirected python 3.10 to check packages in the library of python 3.7 for convenience. Issue was the installed tokenizers package was for python 3.7. Reinstalling pacakge for python 3.10 solved the issue. For people encountered the same issue, run following command:

py -3.10 -m pip install tokenizers

**Comment by LouisYYC** [comment]
> use python 3.10

thanks for the hint
